name: CI Flask App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Lint with Flake8
        run: flake8 src/ --max-line-length=120 --ignore=E402,W503

      - name: Run tests
        run: pytest
        env:
          APPLICATION_POSTGRES_HOST: localhost
          APPLICATION_POSTGRES_USER: postgres
          APPLICATION_POSTGRES_PW: postgres
          APPLICATION_POSTGRES_DB: postgres
          APPLICATION_POSTGRES_PORT: 5432
